
language: minimal

cache:
  directories:
  - $HOME/.ccache

env:
  global:
    - USE_CCACHE=true

addons:
  apt:
    packages:
    - curl
    - gcc-multilib
    - g++-multilib
    - gperf
    - lib32ncurses5-dev
    - lib32z-dev
    - libc6-dev-i386
    - libgl1-mesa-dev
    - libxml2-utils
    - lzop
    - maven
    - schedtool
    - xsltproc
    - python3

before_install:
    - sudo sh -c "curl https://storage.googleapis.com/git-repo-downloads/repo > /bin/repo && chmod a+x /bin/repo"

script:
    - ccache -M 30G
    - sudo sh -c "mkdir /build && chown $(whoami):$(whoami) /build" && cd /build
    - git config --global color.ui false
    - repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-5.1 --depth=1
    - repo sync --no-clone-bundle --no-tags -j$(nproc)
    - mkdir device/huawei && cp -r $TRAVIS_BUILD_DIR device/huawei/HWLUA
    - source build/envsetup.sh
    - lunch omni_HWLUA-eng
    - make -j$(nproc) recoveryimage

deploy:
    provider: releases
    api_key: $GitOAUTHToken
    file: "/build/out/target/product/HWLUA/recovery.img"
    skip_cleanup: true
on:
